---
# Create sparkuser home directory of hdfs
# written by bodhi wang
# jyxz5@qq.com
# Apr 10, 2018
- hosts: compute1.xxx.com,compute2.xxx.com
  become: yes
  become_user: root

  #vars:
  #  TMP_STR: "    "

  tasks:
   - name: Install public signing key of elastic.
     rpm_key: 
       key: "{{item}}"
       state: present
     with_items:
       - https://packages.elastic.co/GPG-KEY-elasticsearch
     tags:
       - elk

   - name: Add repository elastic-6.x
     yum_repository:
       name: elastic-6.x
       description: Elastic repository for 6.x packages
       baseurl: https://artifacts.elastic.co/packages/6.x/yum
       gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
       gpgcheck: yes
       #repo_gpgcheck: yes
       enabled: yes
     tags:
       - elk

   - name: Install filebeat.
     yum:
       name: "{{item}}"
       state: present
     with_items:
       - filebeat
     tags:
       - elk

   - name: Copy public key file to target host
     copy:
       src:  logstash-forwarder.crt
       dest: /etc/pki/tls/certs/logstash-forwarder.crt
       owner: root
       group: root
       mode: 0644
       force: yes
     tags:
       - elkcrt
    
   - name: Copy filebeat configuration file to target host
     copy:
       src: filebeat.yml.compute
       dest: /etc/filebeat/filebeat.yml
       owner: root
       group: root
       mode: 0644
       force: yes
     tags:
       - elk

   - name: Modify /etc/hosts
     lineinfile:
       path: /etc/hosts
       regexp: '^10.13.1.103 '
       line: '10.13.1.103 elk.xxx.com'
     tags:
       - elk
    
   - name: Start filebeat service
     service:
       name: "{{item}}"
       state: started
       enabled: yes
     with_items:
       - filebeat
     tags:
       - elk
