---
# Create sparkuser home directory of hdfs
# written by bodhi wang
# jyxz5@qq.com
# Dec 26, 2017
- hosts: controller.xxx.com
  become: no

  tasks:
   - name: create project
     os_project: 
       name: demoproject
       state: present
       description: demodescription
       cloud: "admin"
