---
# upload image
# written by bodhi wang
# jyxz5@qq.com
# Mar 25, 2018
- hosts: controller.xxx.com
  become: no

  tasks:
  # Upload an image from a local file named kali-for-stack.qcow2
  - os_image:
     cloud: dai
     state: present
     container_format: bare
     disk_format: qcow2
     name: kali-for-stack
     filename: Downloads/kali-for-stack.qcow2
     properties:
       cpu_arch: x86_64
    register: result

  - debug:
     var: result

