---
- hosts: zabbix
  become: yes
  become_user: root
  
  vars:
   - password: "057ea0c6b2c36f85b320"

  tasks:
   - name: change password of root user
     shell: echo "root:{{password}}" | chpasswd 

